name: 'Release 🚀'

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v4
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.credentials.outputs.token }}
          fetch-depth: 0

      - uses: myparcelnl/actions/yarn-install@v4

      - uses: myparcelnl/actions/semantic-release@v4
        with:
          token: ${{ steps.credentials.outputs.token }}
